config/routes.rb
Reservester::Application.routes.draw do

  root to: "welcome#index"

  devise_for :users
  
  resources :categories
  resources :restaurants do 
    resources :stars
    resources :reservations 
  end



  get 'dashboard', :controller => 'users', :action => 'dashboard'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :restaurants 
  
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  
  has_many :restaurants, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: :true, length: { minimum: 5 }
  validates :email, presence: :true
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  
  belongs_to :restaurant

  validates :email, presence: :true 
  validates :datetime, presence: :true
  validates :message, presence: :true

end

app/models/restaurant.rb
 class Restaurant < ActiveRecord::Base
  
  belongs_to :user 
  has_many :stars 
  has_many :users, through: :stars 
  has_many :starred_by, through: :stars, source: :user 

  has_many :reservations, dependent: :destroy
  accepts_nested_attributes_for :reservations, :reject_if => lambda { |a| a[:content].blank? }
  has_and_belongs_to_many :categories 
  accepts_nested_attributes_for :categories 

  validates :name, presence: true
  validates :user, presence: true
  validates :description, presence: true,
              uniqueness: true,
              length: { minimum: 5 }

  mount_uploader :photo, PhotoUploader
  mount_uploader :menu, MenuUploader

  geocoded_by :address
  after_validation :geocode 


  def category_tokens(ids)
    self.category_ids = ids.split(",")
  end

end

app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :restaurants, dependent: :destroy
  has_many :stars
  has_many :starred_restaurants, through: :stars, source: :restaurant
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: :true, length: { minimum: 5 }
  validates :email, presence: :true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?



  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :set_restaurant, :only => [ :show ]


  def index 
    @categories = Category.all 
  end

  def show 
    @restaurants = Restaurant.where(:categories => {:id => params[:id]}).includes(:categories).all
  end 


  private 
  def set_restaurant
    @category = Category.find(params[:id])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_filter :set_reservation, :except => [ :index, :new, :create ]

  def index
    @reservation = Reservation.all
  end

  def show
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if verify_recaptcha() && @reservation.save
      @restaurant = Restaurant.find(@reservation.restaurant_id)
      @user = User.find(@restaurant.user_id)
      #Notifier.send_reservation_email(@owner, @reservation).deliver
      redirect_to restaurants_path
    else
      redirect_to restaurants_path
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @reservation.destroy
    redirect_to restaurants_path
  end

  private
  def reservation_params 
    params.require(:reservation).permit(:email, :datetime, :message, :restaurant_id)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_filter :authenticate_user!, :only => [:new, :create]
  before_filter :set_restaurant, :except => [:index, :new, :create]
  
  def index
    @restaurants = Restaurant.all
  end

  def show
    @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
    end
    @reservation = Reservation.new
  end

  def new
      @restaurant = Restaurant.new
      @restaurant.reservations.build
  end

  def create 
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    params[:restaurant][:user_ids] ||= []
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy 
    redirect_to restaurants_path
  end 

  def star 
    type = params[:type]
    if type == "star"
      current_user.starred_restaurants << @restaurant 
      redirect_to :back, notice: "You starred #{@restaurant.name}"
    elsif type == "unstar"
      current_user.starred_restaurants.delete(@restaurant)
      redirect_to :back, notice: "You unstarred #{@restaurant}"
    end
  end

  private 

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, 
                  :description, :photo, :menu, :reservation, :category_ids => [] )
  end

  def set_restaurant 
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def dashboard 
    @restaurants = Restaurant.find(:all, :conditions => { :user_id => current_user.id })
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def owner?
    if user_signed_in? && current_user.id == @restaurant.user_id 
      return true
    end
    return false
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Category</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category_path(category) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<h2> There's 
  <%= pluralize(@restaurants.count, 'restaurant') %>
  in the 
  <%= @category.name %>
  category. 
</h2>

<p>
  <% @restaurants.each do |restaurant| %>
  <%= link_to restaurant.name, restaurant_path(restaurant) %>
  <br/> 
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">

  <title>Reservester</title>
  <%= stylesheet_link_tag    "application", "token-input-facebook", media: "all" %>
  <%= javascript_include_tag "application", "jquery.tokeninput" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand", href="/">Reservester</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Restaurants", restaurants_path %></li>
            <li><%= link_to "Categories", categories_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Owner Dashboard", dashboard_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>

app/views/notifier/send_reservation_email.erb
<!DOCTYPE html> 
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>

  <body>
    <h1>
      You have a new reservation! 
    </h1>
    <p>
      Email: <%= @reservation.email %><br/>
      Date/Time: <%= @reservation.datetime %><br/>
      Message: <%= @reservation.message %><br/>
    </p>
  </body>
</html>

app/views/reservations/show.html.erb
This is the show page.

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => { :"data-validate" => 'parsley', :class => 'form-horizontal', :multipart => true } do |f| %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', :"data-required" => true, :"data-required-message" => "Enter a name" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field', :"data-required" => true, :"data-required-message" => "Enter a description of your restaurant" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field', :"data-required" => true, :"data-required-message" => "Enter an address" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'text_field', :"data-required" => true, :"data-type" => "phone", :"data-required-message" => "Cuz I just want your number, giiiiirl" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :photo, :class=> 'control-label' %>
    <div class="controls">
      <%= f.file_field :photo, :class => 'file_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :menu, :class=>'control-label' %>
    <div class='controls'>
      <%= f.file_field :menu, :class=>'file_field' %>
    </div>
  </div>

    <div class="control-group">
    <% for category in Category.find(:all) %>
    <div class="controls checkbox inline" >
      <%= check_box_tag "restaurant[category_ids][]", category.id, @restaurant.categories.include?(category)  %>
      <%= category.name %>
    </div>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                restaurants_path, :class => 'btn' %>
  </div>
  
<% end %>

app/views/restaurants/_reservation_form.html.erb
<%= form_for [ @restaurant, @reservation ], :html => { :"data-validate" => 'parsley', :class => 'form-horizontal', :multipart => true } do |f| %>

 <h1>
    Reserverate it. 
  </h1>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.email_field :email, :class => 'email_field', :"data-required" => true %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :datetime, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_field :datetime, :class => 'datetime_field', :"data-required" => true, :"data-required-message" => "Enter a proper date and time" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :message, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :message, :class => 'text_area', :"data-required" => true %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.hidden_field :restaurant_id, :value => @restaurant.id %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= recaptcha_tags %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit "Submit reserveration", :class => 'btn btn-primary' %>     
  </div>

<% end %>

app/views/restaurants/_reservation_show.html.erb
<h1>
  Reserverations
</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date/ Time</th>
      <th>Email Address</th>
      <th>Message</th>
    </tr>
  </thead>
  
  <tbody>
    <% @restaurant.reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.datetime %></td>
      <td><%= reservation.email %></td>
      <td><%= reservation.message %></td>
      <td><%= link_to "Mark as confirmed", [@restaurant, reservation], :method => :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/edit.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurants/index.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Thumbnail</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= image_tag restaurant.photo_url(:thumb).to_s %></td>
        <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td>
        <% restaurant.categories.each do |category| %>
        <%= link_to category.name, category_path(category) %>
        <% end %><br /></td>
        <td>
          <% if user_signed_in? && current_user.id == restaurant.user_id %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_restaurant_path(restaurant), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        restaurant_path(restaurant),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_restaurant_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/restaurants/new.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New #{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= render :partial => 'form' %>

app/views/restaurants/show.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>

<dl class="dl-horizontal">
  <dt><strong>Owner:</strong></dt>
  <dd><%= User.find(@restaurant.user_id).name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @restaurant.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @restaurant.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @restaurant.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @restaurant.phone %></dd>
  <% if @restaurant.categories != [] %>
    <% if @restaurant.categories.length == 1 %>
      <dt><strong>Category:</strong></dt>
    <% else %>
     <dt><strong>Categories:</strong></dt>
    <% end %>
    <% @restaurant.categories.each do |category| %>
    <dd><%= link_to category.name, category_path(category) %></dd>
    <% end %>
  <% end %>
  <dt><strong>Stars:</strong></dt>
  <dd><%= @restaurant.stars.count %></dd>
</dl>

</div>

  <div class="form-actions">
    <% if owner? %>
      <%= link_to t('.back', :default => t("helpers.links.back")),
                  restaurants_path, :class => 'btn'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_restaurant_path(@restaurant), :class => 'btn' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  restaurant_path(@restaurant),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
    <% elsif current_user %>
     <%= link_to "Star this restaurant", new_restaurant_star_path %>
    <% end %>
  </div>


<p>
  <img class="img-rounded">
    <%= image_tag @restaurant.photo_url(:masthead).to_s %>
  </img>
</p>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>


<% if owner? %>
  <%= render :partial => 'reservation_show' %>
<% else %>
  <%= render :partial => 'reservation_form' %>
<% end %>




<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/stars/index.html.erb
<h1>Stars</h1>

This is the stars page. 

app/views/users/dashboard.html.erb
<h1>The one dashboard to rule them all</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.phone %></td>
      <td><%= restaurant.description %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<h1>WELCOME TO RESERVESTER</h1>

<%= link_to "Restaurants", restaurants_path %>
<%= link_to "New Restaurant", new_restaurant_path %>